# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "discount-testing"
client_id = "79ddcf21f80a32a2cb0c4e715bcd5583"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,read_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "development-store-nikhita.myshopify.com"
